# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneBank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneBank
	pod 'SVProgressHUD'
	pod 'Alamofire', '~> 5.0.0-rc.3'
	pod 'SwiftyJSON', '~> 4.0'
	source 'https://github.com/CocoaPods/Specs.git'
	pod 'FileBrowser', '~> 1.0'

end
